### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [felfert/watools#1]
Hi
The following lines have cryptographic API misuses. <br> File name => src/main/java/com/github/felfert/watools/WhatsAppCryptoInputStream.java: Line number => 168: API name => Cipher:Operation on object of type javax.crypto.Cipher object not completed. Expected call to update, doFinal<BR> File name => src/main/java/com/github/felfert/watools/WhatsAppCryptoInputStream.java: Line number => 169: API name => SecretKeySpec:<BR> File name => src/main/java/com/github/felfert/watools/WhatsAppCryptoInputStream.java: Line number => 240: API name => MessageDigest:First parameter (with value "MD5") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => src/main/java/com/github/felfert/watools/WhatsAppCryptoInputStream.java: Line number => 169: API name => IvParameterSpec:<BR> File name => src/main/java/com/github/felfert/watools/WhatsAppCryptoInputStream.java: Line number => 133: API name => MessageDigest:<BR> File name => src/main/java/com/github/felfert/watools/WhatsAppCryptoInputStream.java: Line number => 169: API name => SecretKeySpec:<BR> File name => src/main/java/com/github/felfert/watools/WhatsAppCryptoInputStream.java: Line number => 133: API name => MessageDigest:<BR>

**Comment by felfert** [comment]
Running some automated code analysis tool without actually understanding it, is bad practice.
